on:
    push:
      branches: consumer #change this to your branch name
  
name: Deploy to AWS

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_REGION: 'ap-southeast-2'

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
        aws-account: ${{ env.AWS_ACCOUNT }}

    - name: npm install
      id: npm-install
      run: 
        cd ./build/cdk;
        npm install;
        npm run build;

    - name: cdk bootstrap
      id: cdk-bootstrap
      run:
        cdk bootstrap

    - name: Deploy app
      id: deploy-app

      run: 
        cd ./build/cdk;
        npm run cdk deploy -- 
          --strict
          --verbose
          --require-approval never
          --context Account=$AWS_ACCOUNT
          --context AppName=billing-alert
  